	PROGRAM COUNT_PHOT_VALUES
	IMPLICIT NONE
!
	INTEGER COUNT_DATA
	INTEGER COUNT_LEVS
	INTEGER NC
!	
	CHARACTER*200 STRING
	CHARACTER*80 FILENAME
!
	WRITE(6,*)'Input PHOT file name'
	READ(5,*)FILENAME
!
	COUNT_LEVS=0
	COUNT_DATA=0
!
	OPEN(UNIT=10,FILE=FILENAME,STATUS='OLD',ACTION='READ')
	DO WHILE (1 .EQ. 1)
	  READ(10,FMT='(A)',END=100)STRING
          IF(INDEX(STRING,'!Number of cross-section points') .NE. 0)THEN
	    COUNT_LEVS=COUNT_LEVS+1
	    READ(STRING,*)NC
	    COUNT_DATA=COUNT_DATA+NC
	  END IF
	END DO
100	CONTINUE
!
	WRITE(6,*)'Numer of levels is ',COUNT_LEVS
	WRITE(6,*)'Number of data values is',COUNT_DATA
!
	STOP
	END
