	SUBROUTINE ALLOCATE_WSE_ARRAYS(ND)
	USE MOD_CMFGEN
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER LUER,ERROR_LU
	INTEGER J,NS
	INTEGER IOS
	INTEGER ID
	EXTERNAL ERROR_LU
!
	IOS=0
	DO ID=1,NUM_IONS
	  IF(ATM(ID)%XzV_PRES)THEN
	    J=ATM(ID)%N_XzV_PHOT
	    NS=ATM(ID)%NXzV
            ALLOCATE (ATM(ID)%WSXzV(NS,ND,J),STAT=IOS)
            IF(IOS .EQ. 0)ALLOCATE (ATM(ID)%WCRXzV(NS,ND,J),STAT=IOS)
            IF(IOS .EQ. 0)ALLOCATE (ATM(ID)%dWSXzVdT(NS,ND,J),STAT=IOS)
            IF(IOS .EQ. 0)ALLOCATE (ATM(ID)%dWCRXzVdT(NS,ND,J),STAT=IOS)
	    IF(IOS .NE. 0)THEN
	      LUER=ERROR_LU()
	      WRITE(LUER,*)'Error -- unable to allocate quarature arrays in allocate_wse_arrays.f'
	      WRITE(LUER,*)'IOS=',IOS
	      STOP
	    END IF
	  END IF
	END DO
!
	RETURN
	END
