	MODULE OLD_GRID_MODULE
!
          REAL(10), ALLOCATABLE :: OLD_R(:)
          REAL(10), ALLOCATABLE :: OLD_T(:)
          REAL(10), ALLOCATABLE :: OLD_V(:)
          REAL(10), ALLOCATABLE :: OLD_SIGMA(:)
          REAL(10), ALLOCATABLE :: OLD_ED(:)
          REAL(10), ALLOCATABLE :: OLD_POP_ATOM(:)
          REAL(10), ALLOCATABLE :: OLD_POPION(:)
          REAL(10), ALLOCATABLE :: OLD_MASS_DENSITY(:)
          REAL(10), ALLOCATABLE :: OLD_CLUMP_FAC(:)
!
          REAL(10), ALLOCATABLE :: OLD_TAU(:)
	  REAL(10), ALLOCATABLE :: OLD_SF(:)
          REAL(10), ALLOCATABLE :: OLD_ESEC(:)
          REAL(10), ALLOCATABLE :: OLD_ROSS_MEAN(:)
          REAL(10), ALLOCATABLE :: OLD_FLUX_MEAN(:)
          REAL(10), ALLOCATABLE :: OLD_KAP_ROSS(:)
          REAL(10), ALLOCATABLE :: OLD_KAP_FLUX(:)
          REAL(10), ALLOCATABLE :: OLD_KAP_ESEC(:)
!
	  REAL(10), ALLOCATABLE :: HYDRO_TAU(:)
	  REAL(10), ALLOCATABLE :: HYDRO_ERROR(:,:)
	  REAL(10), ALLOCATABLE :: HYDRO_ACTUAL_GAMMA(:,:)
	  REAL(10), ALLOCATABLE :: HYDRO_PREDICTED_GAMMA(:,:)
!
	  INTEGER, SAVE :: HYDRO_CNT=0
	  INTEGER OLD_ND
!
	END MODULE OLD_GRID_MODULE
