	SUBROUTINE RD_STORE_3INT(VALUE1,VALUE2,VALUE3,KEY,MUST_BE_PRES,A)
	USE RD_VAR_MOD
	IMPLICIT NONE
	INTEGER VALUE1,VALUE2,VALUE3
	LOGICAL MUST_BE_PRES
	LOGICAL KEY_FOUND
	INTEGER I
	CHARACTER*(*) KEY,A
	CHARACTER*80 STRING
!
	CALL GET_KEY_STRING(STRING,KEY,MUST_BE_PRES,KEY_FOUND)
	IF(.NOT. KEY_FOUND)RETURN
	READ(STRING,*)VALUE1,VALUE2,VALUE3
	WRITE(STRING,'(I8,A,I8,A,I8)')VALUE1,',',VALUE2,',',VALUE3
	I=1
	DO WHILE(I.LE. LEN_TRIM(STRING))
	  IF(STRING(I:I) .EQ. ' ')THEN
	    STRING(I:)=STRING(I+1:)
	  ELSE
	     I=I+1
	  END IF
	END DO
	WRITE(LUO,10)TRIM(STRING),TRIM(KEY),TRIM(A)
10	FORMAT(A,T18,'[',A,']',T35,A)
!
	RETURN
	END
