	SUBROUTINE SMOOTH_POPS_AS_WE_ITERATE(POPS,STEQ_VALS,ND,NT)
	USE MOD_CMFGEN
	USE CONTROL_VARIABLE_MOD
	IMPLICIT NONE
!
! Altered 19-May-2019 _ Still under devlopment.
!
	INTEGER ND
	INTEGER NT
	REAL*8 POPS(NT,ND)
	REAL*8 STEQ_VALS(NT,ND)
	INTEGER DONE(NT)
!
!	REAL*8 RATIO(NT,ND)
	INTEGER LUOUT
	INTEGER I,J,K,L
	INTEGER ISPEC
	INTEGER ID
	REAL*8 T1,T2,T3
!
	WRITE(6,*)'Entering SMOOTH_POPS_AS_WE_ITERATE'; 	FLUSH(UNIT=6)
!
!	CALL GET_LU(LUOUT,'In SMOOTH_POPS_AS_WE_ITERATE')
!	CALL WR2D_V2(POPS,NT,ND,'POPS','*',.TRUE.,LUOUT)
!	CALL WR2D_V2(RATIO,NT,ND,'Ratio','*',.TRUE.,LUOUT)
!	CLOSE(UNIT=LUOUT)
!
	WRITE(6,*)'Min of STEQ_VALS array is',MINVAL(STEQ_VALS)
	WRITE(6,*)'Max of STEQ_VALS array is',MAXVAL(STEQ_VALS)
!
	DONE=0
	DO L=ND-5,1,-1
	  DO ISPEC=1,NUM_SPECIES
	    DO ID=SPECIES_BEG_ID(ISPEC),SPECIES_END_ID(ISPEC)-1
	      K=0; IF(ID .EQ. SPECIES_END_ID(ISPEC)-1)K=1
	      DO I=1,ATM(ID)%NXzV+K
	        J=ATM(ID)%EQXzV+I-1
	        IF(STEQ_VALS(J,L) .GT. 0.998D0 .OR. STEQ_VALS(J,L)  .LT. -1.0D+04)THEN
	          T1=(POPS(J,L+1)/POP_SPECIES(L+1,ISPEC)) / (POPS(J,L+2)/POP_SPECIES(L+2,ISPEC))
	          T2=(POPS(J,L)/POP_SPECIES(L,ISPEC)) / (POPS(J,L+1)/POP_SPECIES(L+1,ISPEC))
	          IF(ABS(LOG10(T1/T2)) .GT. 2 .AND. DONE(J) .LT. 2 .AND.  ABS(LOG10(T1)) .LT. 3)THEN
	            T3=T1*(POPS(J,L+1)/POP_SPECIES(L+1,ISPEC))*POP_SPECIES(L,ISPEC) 
	            WRITE(6,'(A3,2X,4I5,2X,L1,2X,5ES14.4)')' CM',L,ISPEC,ID,I,DONE(J),T1,T2,T3,POPS(J,L),POPS(J,L+1)
	            POPS(J,L)=T3
	            DONE(J)=DONE(J)+1
	          ELSE  IF(ABS(LOG10(T1/T2)) .GT. 5)THEN
	            T3=T1*(POPS(J,L+1)/POP_SPECIES(L+1,ISPEC))*POP_SPECIES(L,ISPEC) 
	            WRITE(6,'(A3,2X,4I5,2X,L1,2X,5ES14.4)')' CM',L,ISPEC,ID,I,DONE(J),T1,T2,T3,POPS(J,L),POPS(J,L+1)
	            POPS(J,L)=T3
	            DONE(J)=DONE(J)+1
	          ELSE
	            WRITE(6,'(A3,2X,4I5,2X,L1,2X,5ES14.4)')'CNM',L,ISPEC,ID,I,DONE(J),T1,T2,T3,POPS(J,L),POPS(J,L+1)
	          END IF
	        END IF
	        DONE(J)=0
	      END DO
	    END DO
	  END DO
	END DO
	WRITE(6,*)'Exiting SMOOTH_POPS_AS_WE_ITERATE'; 	FLUSH(UNIT=6)
!
	RETURN
	END 
