	PROGRAM TST_LOOP
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER, PARAMETER :: NT=1400
	INTEGER, PARAMETER :: NB=3
	INTEGER, PARAMETER :: ND=100
!
	REAL(KIND=LDP) VJ(NT,NB,ND)
	REAL(KIND=LDP) VJ_SUM(NT,NB,ND)
	REAL(KIND=LDP) VJ_SUM2(NT,NB,ND)
	REAL(KIND=LDP) T(ND)
	REAL(KIND=LDP) RJ(ND)
	REAL(KIND=LDP) OLDJ(ND)
	REAL(KIND=LDP) T1
!
	INTEGER I,J,K,L
	INTEGER ISEED
!
	ISEED=-12345678
	DO L=1,ND
	  T(L)=1.0_LDP+(L-1)*0.01_LDP
	  OLDJ(L)=RAN(ISEED)
	  DO K=1,NB
	    DO I=1,NT
!	       VJ(I,K,L)=0.2
	       VJ(I,K,L)=RAN(ISEED)
	    END DO
	  END DO
	END DO
	VJ_SUM(:,:,:)=0.0_LDP
	VJ_SUM2(:,:,:)=0.0_LDP
	RJ(:)=0.0_LDP
!
	CALL TUNE(1,'LOOP:')
	DO I=1,100
	  DO L=1,ND
	     T1=EXP(-4.7994_LDP/T(L))
	     VJ_SUM(:,:,L)=VJ_SUM(:,:,L)+T1*VJ(:,:,L)
	     VJ_SUM2(:,:,L)=VJ_SUM2(:,:,L)-2.0_LDP*T1*VJ(:,:,L)
	     RJ(L)=RJ(L)+OLDJ(L)
	  END DO
	END DO
	CALL TUNE(2,'LOOP:')
!
	CALL TUNE(1,'LOOP')
	DO I=1,100
	  DO L=1,ND
	    T1=EXP(-4.7994_LDP/T(L))
	    DO K=1,NB
	      DO J=1,NT
	        VJ_SUM(J,K,L)=VJ_SUM(J,K,L)+T1*VJ(J,K,L)
	        VJ_SUM2(J,K,L)=VJ_SUM2(J,K,L)-2.0_LDP*T1*VJ(J,K,L)
	      END DO
	    END DO
	    RJ(L)=RJ(L)+OLDJ(L)
	  END DO
	END DO
	CALL TUNE(2,'LOOP')
!
	CALL TUNE(1,'LOOP2')
	DO I=1,100
	  DO L=1,ND
	    DO K=1,NB
	      DO J=1,NT
	        VJ_SUM(J,K,L)=VJ_SUM(J,K,L)+VJ(J,K,L)
	        VJ_SUM2(J,K,L)=VJ_SUM2(J,K,L)-2.0_LDP*VJ(J,K,L)
	      END DO
	    END DO
	    RJ(L)=RJ(L)+OLDJ(L)
	  END DO
	END DO
	CALL TUNE(2,'LOOP2')
!
	CALL TUNE(1,'LOOP2:')
	DO I=1,100
	  DO L=1,ND
	     VJ_SUM(:,:,L)=VJ_SUM(:,:,L)+VJ(:,:,L)
	     VJ_SUM2(:,:,L)=VJ_SUM2(:,:,L)-2.0_LDP*VJ(:,:,L)
	     RJ(L)=RJ(L)+OLDJ(L)
	  END DO
	END DO
	CALL TUNE(2,'LOOP2:')
!
!
	CALL TUNE(3,' ')
!
	STOP
	END
