	SUBROUTINE LOGVEC(X,YV,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
C
C Altered 20-Mar-1998: YV now passed as REAL(KIND=LDP)
C
	INTEGER ND,I
	REAL(KIND=LDP) X(ND)
	REAL(KIND=LDP) YV(ND)
C
	DO I=1,ND
	  YV(I)=LOG10(X(I))
	END DO
C
	RETURN
	END
