	SUBROUTINE RD_NON_THERM_SPEC(FELEC,FION,FEXC,ND,FILE_NAME,LU_IN,IOS)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER LU_IN
	INTEGER IOS
	REAL(KIND=LDP) FELEC(ND)
	REAL(KIND=LDP) FION(ND)
	REAL(KIND=LDP) FEXC(ND)
	CHARACTER(LEN=*) FILE_NAME
!
	REAL(KIND=LDP) T1
	INTEGER I
	CHARACTER(LEN=132) STRING
!
	OPEN(UNIT=LU_IN,FILE=FILE_NAME,STATUS='OLD',ACTION='READ',IOSTAT=IOS)
	IF(IOS .NE. 0)RETURN
!
	DO WHILE(INDEX(STRING,'Felec') .EQ. 0)
	  READ(LU_IN,'(A)')STRING
	END DO
!
	DO I=1,ND
	  READ(LU_IN,*)T1,FELEC(I),T1,FION(I),T1,FEXC(I)
	END DO
!
	CLOSE(LU_IN)
	RETURN
	END
