C
C Set the SAVE vector for an NG acceleration.
C
	SUBROUTINE SETFORNG(RJ,PREVRJ,ITNUM,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
	INTEGER I,ITNUM,ND
	REAL(KIND=LDP) RJ(ND),PREVRJ(4,ND)
C
	DO I=1,ND
	  PREVRJ(ITNUM,I)=RJ(I)
	END DO
C
	RETURN
	END	
