	SUBROUTINE UPDATE_POPS(HE2,HE2LTE,EDGE,N,ND,TOLD,TNEW)
	USE SET_KIND_MODULE
	IMPLICIT NONE
	INTEGER N,ND
	REAL(KIND=LDP) HE2(N,ND),HE2LTE(N,ND),EDGE(N)
	REAL(KIND=LDP) TOLD(ND),TNEW(ND)
C
	COMMON/CONSTANTS/ CHIBF,CHIFF,HDKT,TWOHCSQ
	REAL(KIND=LDP) CHIBF,CHIFF,HDKT,TWOHCSQ
C
	INTEGER I,J
	REAL(KIND=LDP) T1,T2,T3
C
	DO I=1,ND
	  T1=(TOLD(I)/TNEW(I) )**1.5
	  T2=HDKT*(1.0D0/TNEW(I)-1.0D0/TOLD(I))
	  DO J=1,N
	    T3=T1*EXP(T2*EDGE(J))
	    HE2(J,I)=HE2(J,I)*T3
	    HE2LTE(J,I)=HE2LTE(J,I)*T3
	  END DO
	END DO
C
	RETURN
	END
