	SUBROUTINE WR_SPEC_SUM(XSPEC,NUM_FRAC,MASS_FRAC,ND)
	USE MOD_DISP
	IMPLICIT NONE
!
	INTEGER ND
	LOGICAL NUM_FRAC
	LOGICAL MASS_FRAC
	CHARACTER(LEN=*) XSPEC
!
	REAL*8 T1
	REAL*8 ATOMIC_MASS_UNIT
	REAL*8 VALUE(NSPEC)
	INTEGER ISPEC_STORE(NSPEC)
	INTEGER IWORK(NSPEC)
	INTEGER INDX(NSPEC)
!
	EXTERNAL ATOMIC_MASS_UNIT
	INTEGER, PARAMETER :: NSTR=10
	CHARACTER(LEN=80) STRING(NSTR)
!
	LOGICAL, PARAMETER :: L_FALSE=.FALSE.
	INTEGER I,J,K
	INTEGER DPTH_INDX
	INTEGER ISPEC
!
	STRING=' '
	DPTH_INDX=1
	DO K=1,3
	  IF(K .EQ. 2)DPTH_INDX=(ND+1)/2
	  IF(K .EQ. 3)DPTH_INDX=ND
	  DO ISPEC=1,NSPEC
	    IF(POPDUM(DPTH_INDX,ISPEC) .GT. 0.0D0)THEN
	      J=J+1
	      IF(NUM_FRAC)THEN
	        VALUE(J)=POPDUM(DPTH_INDX,ISPEC)/POP_ATOM(DPTH_INDX)+1.0D-100
	      ELSE IF(MASS_FRAC)THEN
	        T1=AT_MASS(ISPEC)*ATOMIC_MASS_UNIT()
	        VALUE(J)=T1*POPDUM(DPTH_INDX,ISPEC)/MASS_DENSITY(DPTH_INDX)+1.0D-100
	      ELSE
	        VALUE(J)=POPDUM(DPTH_INDX,ISPEC)+1.0D-100
	      END IF
	      ISPEC_STORE(J)=ISPEC
	    END IF
	  END DO
	  CALL INDEXX(NSPEC,VALUE,INDX,L_FALSE)
	  CALL SORTINT(NSPEC,ISPEC_STORE,INDX,IWORK)
!
	  DO I=1,NSTR
	    IF(ISPEC_STORE(I) .EQ. 0)EXIT
	    J=LEN_TRIM(STRING(I))+1
	    IF(J .NE. 1)J=J+5
	    ISPEC=ISPEC_STORE(I)
	    T1=VALUE(ISPEC)
            WRITE(STRING(I:)(J:),'(A6,2X,F9.6,3X,ES9.2,5X)')TRIM(SPECIES(ISPEC)),T1,LOG10(T1)
	  END DO
	END DO
!
        WRITE(6,'(A)')' '
	IF(NUM_FRAC)THEN
	  WRITE(6,'(A)')' Number fraction (NF) and Log(NF) at inner boundary'
	ELSE IF(MASS_FRAC)THEN
	  WRITE(6,'(A)')' Mass fraction (MF) and Log(MF) at inner boundary'
	ELSE
	  WRITE(6,'(A)')' Number denistury (ND) and Log(ND) at inner boundary'
	END IF
	WRITE(6,'(A)')' '
!
	DO I=1,NSTR
	  IF(STRING(I) .NE. ' ')THEN
	    WRITE(6,'(A)')STRING(I)
	  END IF
	END DO
!
	RETURN
	END
