	SUBROUTINE COMP_VAR_JREC(JREC,dJRECdT,JPHOT,
	1                  JREC_CR,JPHOT_CR,BPHOT_CR,
	1                  RJ,EMHNUKT,T,NU,FQW,TWOHCSQ,HDKT,ND,COMP_NEW_CONT)
	USE SET_KIND_MODULE
	IMPLICIT NONE
C
	INTEGER ND
	REAL(KIND=LDP) JREC(ND)
	REAL(KIND=LDP) dJRECdT(ND)
	REAL(KIND=LDP) JPHOT(ND)
	REAL(KIND=LDP) JREC_CR(ND)
	REAL(KIND=LDP) JPHOT_CR(ND)
	REAL(KIND=LDP) BPHOT_CR(ND)
	REAL(KIND=LDP) RJ(ND)
	REAL(KIND=LDP) EMHNUKT(ND)
	REAL(KIND=LDP) T(ND)
	REAL(KIND=LDP) NU
	REAL(KIND=LDP) FQW
	REAL(KIND=LDP) HDKT,TWOHCSQ
	LOGICAL COMP_NEW_CONT
C
	REAL(KIND=LDP) T1,T2
	INTEGER I
C
	IF(COMP_NEW_CONT)THEN
	  JREC(:)=0.0D0
	  dJRECdT(:)=0.0D0
	  JPHOT(:)=0.0D0
	  JREC_CR(:)=0.0D0
	  JPHOT_CR(:)=0.0D0
	  BPHOT_CR(:)=0.0D0
	END IF
C
	T1=TWOHCSQ*(NU**3)
	DO I=1,ND
	  T2=(T1+RJ(I))*EMHNUKT(I)*FQW/NU
	  JREC(I)=JREC(I)+T2
	  dJRECdT(I)=dJRECdT(I)+T2*HDKT*NU/T(I)/T(I)
	  JPHOT(I)=JPHOT(I)+RJ(I)*FQW/NU
	  JREC_CR(I)=JREC_CR(I)+T2*NU
	  JPHOT_CR(I)=JPHOT_CR(I)+RJ(I)*FQW
	  BPHOT_CR(I)=BPHOT_CR(I)+T1*FQW*EMHNUKT(I)/(1.0D0-EMHNUKT(I))
	END DO
C
	RETURN
	END
