	SUBROUTINE DP_ZERO(Z,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER ND
	REAL(KIND=LDP) Z(ND)
!
! Altered 13-Mar-2013 : WORKSHARE installed
! Altered 28-May-1996 : F90 updated, IMPLCIT NONE installed.
!
!$OMP PARALLEL WORKSHARE
!
	Z=0.0_LDP
!
!$OMP END PARALLEL WORKSHARE
!
	RETURN
	END
