	SUBROUTINE SET_DC_LTE_V2(XzVLTE,DXzV,EDGE,NXzV,T,TMIN,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
! Altered  9-Dec-2013:  Changed way code handles TMIN_LOC -- still needs development.
! Created 24-Feb-2013.  Returns Log (dep. coef.)
!                       Based on SET_DC_LTE
!
	INTEGER NXzV
	INTEGER ND
	REAL(KIND=LDP) XzVLTE(NXzV,ND)
	REAL(KIND=LDP) DXzV(ND)
	REAL(KIND=LDP) T(ND)
	REAL(KIND=LDP) EDGE(NXzV)
	REAL(KIND=LDP) TMIN
!
! Constants for opacity etc. These are set in CMFGEN.
!
        COMMON/CONSTANTS/ CHIBF,CHIFF,HDKT,TWOHCSQ
        REAL(KIND=LDP) CHIBF,CHIFF,HDKT,TWOHCSQ
	REAL(KIND=LDP) TMIN_LOC
	INTEGER I,J
!
	TMIN_LOC=TMIN*(1.0_LDP+(MAX(0.0_LDP,(EDGE(1)-3.5_LDP))/20.0_LDP))
	DO I=1,ND
	  DXzV(I)=1.0_LDP
	  IF(T(I) .GT. TMIN_LOC)THEN
	    XzVLTE(:,I)=0.0_LDP
	  ELSE
	    DO J=1,NXzV
	      XzVLTE(J,I)=HDKT*EDGE(J)*(1.0_LDP/TMIN_LOC-1.0_LDP/T(I))
	    END DO
	  END IF
	END DO
!
	RETURN
	END
