	PROGRAM TST_WR
	IMPLICIT NONE
	INTEGER*4, PARAMETER :: N=1020
	INTEGER*4, PARAMETER :: ND=1600
	INTEGER*4, PARAMETER :: LU=10
	INTEGER*4, PARAMETER :: ISIX=6
	INTEGER*4 I,J
	REAL*8 F(N,ND)
!
	DO I=1,ND
	  DO J=1,N
	    F(J,I)=J+(I-1)*N
	  END DO
	END DO
!
	CALL WR2D_V2(F,N,ND,'Testing WR','#',.TRUE.,LU)
	CALL WR2D_V2(F,N,ND,'Testing WR','#',.FALSE.,11)
!
	STOP
	END
