	MODULE MOD_RAY_MOM_STORE
	IMPLICIT NONE
!
	INTEGER ND_STORE
	REAL(10), ALLOCATABLE :: R_STORE(:)
	REAL(10), ALLOCATABLE :: RMID_STORE(:) 
	REAL(10), ALLOCATABLE :: EXT_RMID_STORE(:) 
	REAL(10), ALLOCATABLE :: JNU_STORE(:)
	REAL(10), ALLOCATABLE :: HNU_STORE(:)
	REAL(10), ALLOCATABLE :: NNU_STORE(:)
	REAL(10), ALLOCATABLE :: KNU_STORE(:)
	REAL(10), ALLOCATABLE :: GAM_REL_STORE(:)
!
! General description of radiation field at boundaries.
!
	REAL(10) JPLUS_IB,JMIN_IB
	REAL(10) HPLUS_IB,HMIN_IB
	REAL(10) KPLUS_IB,KMIN_IB
	REAL(10) NPLUS_IB,NMIN_IB
	REAL(10) JPLUS_OB,JMIN_OB
	REAL(10) HPLUS_OB,HMIN_OB
	REAL(10) KPLUS_OB,KMIN_OB
	REAL(10) NPLUS_OB,NMIN_OB
!
	REAL(10) HNU_AT_OB, NNU_AT_OB
	REAL(10) HNU_AT_IB, NNU_AT_IB
	REAL(10) HNU_AT_OB_PREV, NNU_AT_OB_PREV
	REAL(10) HNU_AT_IB_PREV, NNU_AT_IB_PREV
!
	REAL(10) HBC,HBC_PREV,HBC_SAVE
	REAL(10) NBC,NBC_PREV,NBC_SAVE
	REAL(10) IN_HBC,IN_HBC_PREV,IN_HBC_SAVE
!
	REAL(10), ALLOCATABLE :: RMID(:)
	REAL(10), ALLOCATABLE :: H_ON_J(:)
	REAL(10), ALLOCATABLE :: N_ON_J(:)
	REAL(10), ALLOCATABLE :: K_ON_J(:)
	REAL(10), ALLOCATABLE :: KMID_ON_J(:)
	REAL(10), ALLOCATABLE :: NMID_ON_J(:)
	REAL(10), ALLOCATABLE :: NMID_ON_HMID(:)
	REAL(10), ALLOCATABLE :: dlnGRSQJdlnR(:)
!
	REAL(10), ALLOCATABLE :: H_ON_J_PREV(:)
	REAL(10), ALLOCATABLE :: N_ON_J_PREV(:)
	REAL(10), ALLOCATABLE :: K_ON_J_PREV(:)
	REAL(10), ALLOCATABLE :: KMID_ON_J_PREV(:)
	REAL(10), ALLOCATABLE :: NMID_ON_J_PREV(:)
	REAL(10), ALLOCATABLE :: NMID_ON_HMID_PREV(:)
!
	REAL(10), ALLOCATABLE :: H_ON_J_SAVE(:)
	REAL(10), ALLOCATABLE :: N_ON_J_SAVE(:)
	REAL(10), ALLOCATABLE :: K_ON_J_SAVE(:)
	REAL(10), ALLOCATABLE :: KMID_ON_J_SAVE(:)
	REAL(10), ALLOCATABLE :: NMID_ON_J_SAVE(:)
	REAL(10), ALLOCATABLE :: NMID_ON_HMID_SAVE(:)
!
	LOGICAL HN_DEF_ON_NODES
!
	END MODULE MOD_RAY_MOM_STORE
