	MODULE MOD_RD_GAMRAY_CNTRL_VARIABLES
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	REAL(KIND=LDP) :: V_GAUSS
	REAL(KIND=LDP) :: V_INF
	REAL(KIND=LDP) :: V_LINE
	REAL(KIND=LDP) :: V_TAIL
	REAL(KIND=LDP) :: V_BETWEEN
	REAL(KIND=LDP) :: V_END
	REAL(KIND=LDP) :: BLUE_GAUSS
	REAL(KIND=LDP) :: RED_GAUSS
	REAL(KIND=LDP) :: COMP_TAIL_SPLIT_FRAC
	REAL(KIND=LDP) :: EGAM_MIN
	REAL(KIND=LDP) :: EGAM_MAX
!
	INTEGER :: NU_GRID_MAX
	INTEGER :: CHEB_ORDER
	INTEGER :: ANG_MULT
	INTEGER :: GAM_IT
	INTEGER :: GRAY_LINE_MIN
	INTEGER :: GRAY_TAIL_MIN1
	INTEGER :: GRAY_TAIL_MIN2
	INTEGER :: GRAY_TAIL_MIN3
	INTEGER :: GRAY_TAIL_MIN4
	INTEGER :: GRAY_END_MIN
!
	CHARACTER(LEN=10) :: GAM_IB_METH
!
	LOGICAL :: NORM_GAM_LINES
	LOGICAL :: NORM_LINES_ONLY
	LOGICAL :: GRID_TST
	LOGICAL :: GRID_MIN_PTS
	LOGICAL :: OBS_REL_FULL
	LOGICAL :: DO_NORM_ETA
	LOGICAL :: VERBOSE_GAMMA
	LOGICAL :: WRITE_J_DATA
!
	END MODULE MOD_RD_GAMRAY_CNTRL_VARIABLES
