	SUBROUTINE ADJUST_ID_WAVES(XUNIT)
	USE SET_KIND_MODULE
        USE LINE_ID_MOD
	IMPLICIT NONE
!
! Altered 01-Sep-2019 : Changed to read new-format EW file.
!
	CHARACTER(LEN=*) XUNIT
!
	IF(XUNIT .EQ. 'um')THEN
	  ID_WAVE(1:N_EW_IDS)=1.0D-04*ID_WAVE(1:N_EW_IDS)
	  ID_WAVE_OFF(1:N_EW_IDS)=1.0D-04*ID_WAVE_OFF(1:N_EW_IDS)
	ELSE IF(XUNIT .EQ. 'nm')THEN
	  ID_WAVE(1:N_EW_IDS)=1.0D-03*ID_WAVE(1:N_EW_IDS)
	  ID_WAVE_OFF(1:N_EW_IDS)=1.0D-03*ID_WAVE_OFF(1:N_EW_IDS)
	ELSE IF(XUNIT .EQ. 'Ang')THEN
	ELSE
	  WRITE(6,*)'The following XUNIT was not recognized: ',TRIM(XUNIT)
	END IF
!
	RETURN	
	END
