!
! General purpose line plotting routiine.
!
	SUBROUTINE DRAW_LINE_IDS(XPAR,YPAR,EXPCHAR,T_OUT)
	USE LINE_ID_MOD
	USE MOD_COLOR_PEN_DEF
	IMPLICIT NONE
!
	REAL*4 XPAR(2)
	REAL*4 YPAR(2)
	REAL*4 XSTRPOS,YSTRPOS
	REAL*4 XCHAR_SIZE,YCHAR_SIZE
	REAL*4 EXPCHAR
	INTEGER T_OUT
!
	INTEGER, PARAMETER :: IONE=1
	INTEGER, PARAMETER :: ITWO=2
	INTEGER, PARAMETER :: ITHREE=4
	INTEGER, PARAMETER :: IFOUR=4

	INTEGER I,J,K,L
	REAL*4 T1,T2
	CHARACTER(LEN=80) TMP_STR
!
	IF(N_LINE_IDS .NE. 0)THEN
	  CALL PGSCI(IONE)
	  ID_LOC=4
	  ID_ORIENT=90.0D0
	  ID_LOC_PG=1.0D0
!
	  DO I=1,N_LINE_IDS
	    WR_ID(I)=.TRUE.
	    DO J=1,N_OMIT_ID
	      IF( INDEX(LINE_ID(I),TRIM(OMIT_ID(J))//' ') .NE. 0)THEN
	        WR_ID(I)=.FALSE.
	        EXIT
	      END IF
	    END DO
	    DO J=1,N_INC_ID
	      IF(J .EQ. 1)WR_ID(I)=.FALSE.
	      IF( INDEX(LINE_ID(I),TRIM(INC_ID(J))//' ') .NE. 0 )THEN
	        WR_ID(I)=.TRUE.
	        EXIT
	      END IF
	    END DO
	  END DO
!
	  ID_WAVE_OFF(1:N_LINE_IDS)=ID_WAVE(1:N_LINE_IDS)
	  CALL PGQCS(IFOUR,XCHAR_SIZE,YCHAR_SIZE)
	  WRITE(T_OUT,*)'XCHAR_SIZE=',XCHAR_SIZE
	  DO L=1,8
	    DO I=1,N_LINE_IDS-1
	      IF(WR_ID(I))THEN
	        K=I+1
	        DO WHILE(.NOT. WR_ID(K) .AND. K .LT. N_LINE_IDS)
	          K=K+1
	        END DO
	        T1=(ID_WAVE(I)-XPAR(1))*(XPAR(2)-ID_WAVE(2))
	        IF(T1 .GT. 0)THEN
	          IF(ID_WAVE_OFF(I)+XCHAR_SIZE .GT. ID_WAVE_OFF(K))THEN
	            ID_WAVE_OFF(I)=ID_WAVE_OFF(K)-1.1*XCHAR_SIZE
	          END IF
	        END IF
	      END IF
	    END DO
	  END DO
!
	  DO I=1,N_LINE_IDS
	    T1=ID_SCL*ID_Y_OFF(I)
	    ID_VEC_BEG=0.9*(T1-1.0D0)+1.0D0
	    TMP_STR=' '
	    WRITE(TMP_STR,'(F12.2)')ID_WAVE(I)
	    TMP_STR=TRIM(LINE_ID(I))//'-'//ADJUSTL(TMP_STR)
	    IF(.NOT. OBSERVED_WAVE(I))TMP_STR='*'//TMP_STR
	    CALL JUSTIFY_CONVERT_V2(ID_WAVE_OFF(I),T1,ID_LOC,ID_LOC_PG,ID_ORIENT,.TRUE.,
	1                  XSTRPOS,YSTRPOS,TMP_STR,IONE)
	    T1=(XSTRPOS-XPAR(1))*(XPAR(2)-XSTRPOS)
	    T2=(YSTRPOS-YPAR(1))*(YPAR(2)-YSTRPOS)
	    IF(T1 .GT. 0 .AND. T2 .GT. 0)THEN
	      IF(WR_ID(I))THEN
	        CALL PGSCI(ITWO)
	        CALL PGSCH(EXPCHAR*ID_EXPCHAR)
	        CALL PGPTXT(XSTRPOS,YSTRPOS,ID_ORIENT,ID_LOC_PG,TMP_STR)
	        T1=ID_SCL*ID_Y_OFF(I)
	        CALL PGMOVE(ID_WAVE_OFF(I),ID_VEC_BEG)
	        CALL PGDRAW(ID_WAVE(I),ID_VEC_END)
	      END IF
	    END IF
	  END DO
	END IF
!
	RETURN
	END
