	SUBROUTINE GET_LINE_ID_PG(TRANS_NAME,LINE_WAVE,EW,LINE_CENTER,FWHM_KMS)
	USE LINE_ID_MOD
	CHARACTER(LEN=*) TRANS_NAME
	REAL*4 EW
	REAL*4 LINE_CENTER
	REAL*4 FWHM_KS
	REAL*4 LINE_WAVE
!
! Altered 23-Jul-2022: Added LINE_WAVE to call.
! Altered 22-Jul-2022: Better check if ID exits.
!
	INTEGER,PARAMETER :: NMATCH=5
	REAL*4 OFF_STORE(NMATCH)
	INTEGER PNT_STORE(NMATCH)
	INTEGER PNT
!
	INTEGER I,K
	REAL*4 T1
	REAL*4 SHIFT
	REAL*4 TAU_VAL
!
	TRANS_NAME=' '; LINE_WAVE=0.0
	IF(N_LINE_IDS .EQ. 0)THEN
	  RETURN
	END IF
!
	OFF_STORE=1.0D+10
	PNT_STORE=0
	DO I=1,N_LINE_IDS-1
	  T1=2.998D+05*ABS(ID_WAVE(I)/LINE_CENTER-1.0D0)/FWHM_KMS
	  DO K=1,NMATCH
	    IF(T1 .LT. OFF_STORE(K))THEN
	      OFF_STORE(K+1:NMATCH)=OFF_STORE(K:NMATCH-1)
	      OFF_STORE(K)=T1
              PNT_STORE(K)=I
	      EXIT
	    END IF
	  END DO
	END DO
!
! Now decide on best line
!
	IF(PNT_STORE(1) .EQ. 0)THEN
	ELSE
	  I=PNT_STORE(1)
	  TRANS_NAME=FULL_LINE_ID(I)
	  TAU_VAL=TAU(I)
	  LINE_WAVE=ID_WAVE(I)
	  DO K=2,NMATCH
	    IF(OFF_STORE(K) .LT. 0.1)THEN
	      I=PNT_STORE(K)
	      IF(TAU(I) .GT. 3*TAU_VAL)THEN
	        TRANS_NAME=FULL_LINE_ID(I)
	        TAU_VAL=TAU(I)
	        LINE_WAVE=ID_WAVE(I)
	      END IF
	    END IF
	  END DO
	END IF
!
	RETURN
	END
