	MODULE LINE_ID_MOD
	IMPLICIT NONE
!
	INTEGER, PARAMETER :: N_LINE_ID_MAX=5000
!
	LOGICAL OBSERVED_WAVE(N_LINE_ID_MAX)
	CHARACTER(LEN=10) LINE_ID(N_LINE_ID_MAX)
	CHARACTER(LEN=80) FULL_LINE_ID(N_LINE_ID_MAX)
	REAL*4 ID_WAVE(N_LINE_ID_MAX)
	REAL*4 ID_WAVE_OFF(N_LINE_ID_MAX)
	REAL*4 ID_Y_OFF(N_LINE_ID_MAX)
	REAL*4 ID_EW(N_LINE_ID_MAX)
	REAL*4 ID_CONT_FLUX(N_LINE_ID_MAX)
	REAL*4 TAU(N_LINE_ID_MAX)
!
	REAL*4 TAU_CUT
	REAL*4 EW_CUT
	REAL*4 EW_SCALE_FAC
	REAL*4 ID_ORIENT
	REAL*4 ID_SCL
	REAL*4 ID_VEC_BEG
	REAL*4 ID_VEC_END
	REAL*4 ID_EXPCHAR
	REAL*4 CUT_ACCURACY
	REAL*4 ID_LOC_PG
!
	INTEGER N_LINE_IDS
	INTEGER N_EW_IDS
	INTEGER ID_LOC
	INTEGER N_OMIT_ID
	INTEGER N_INC_ID
!
	CHARACTER(LEN=10) OMIT_ID(10)
	CHARACTER(LEN=10) INC_ID(10)
	LOGICAL WR_ID(N_LINE_ID_MAX)
!
	END MODULE LINE_ID_MOD
