	MODULE MOD_CURVE_DATA
	IMPLICIT NONE
!
! Altered 28-MAr-2003: LU_ER changed from 5 to 6.
!
	INTEGER*4, PARAMETER :: MAX_PLTS=50
	INTEGER*4, PARAMETER :: LU_ER=6
	INTEGER*4 IOS
!
	INTEGER*4 NPLTS
	INTEGER*4 NPTS(MAX_PLTS)
	LOGICAL   ERR(MAX_PLTS)
!
	TYPE CURVE_DATA
	  REAL*4, POINTER :: XVEC(:)
	  REAL*4, POINTER :: DATA(:)
	  REAL*4, POINTER :: EMIN(:)
	  REAL*4, POINTER :: EMAX(:)
	END TYPE CURVE_DATA
!
	DATA NPTS/MAX_PLTS*0/
	DATA ERR/MAX_PLTS*.FALSE./
	DATA NPLTS/0/
!
	TYPE (CURVE_DATA) CD(MAX_PLTS)
!
	END MODULE MOD_CURVE_DATA
