	SUBROUTINE SET_PG_TITLES(TIT,NTIT,REMOVE_LAST_COMMA)
	USE MOD_CURVE_DATA
	IMPLICIT NONE
	INTEGER NTIT
	CHARACTER(LEN=*) TIT(NTIT)
	LOGICAL REMOVE_LAST_COMMA
!
	INTEGER I,J,K
!
	TITLE=' '
	TITLE(1:NTIT)=TIT(1:NTIT)
	N_TIT_SET=NTIT
!
	IF(REMOVE_LAST_COMMA)THEN
	  DO I=1,NTIT
	    K=LEN_TRIM(TITLE(I))
	    DO J=K,1,-1
	      IF(TITLE(I)(J:J) .EQ. ',')THEN
	        TITLE(I)=TITLE(I)(1:J-1)//TITLE(I)(J+1:)
	        EXIT
	      END IF
	    END DO
	  END DO
	END IF
!
	RETURN
	END
