	MODULE NUM_CONSTANTS_MOD
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
! Module containing numerical constants that are commonly used.
!
! Created 28-Nov-2023
!
	REAL(KIND=LDP), PARAMETER :: RZERO=0.0_LDP
	REAL(KIND=LDP), PARAMETER :: RONE=1.0_LDP
	REAL(KIND=LDP), PARAMETER :: RTWO=2.0_LDP
	REAL(KIND=LDP), PARAMETER :: RTHREE=3.0_LDP
	REAL(KIND=LDP), PARAMETER :: RFOUR=4.0_LDP
	REAL(KIND=LDP), PARAMETER :: RFIVE=5.0_LDP
	REAL(KIND=LDP), PARAMETER :: RSIX=6.0_LDP
	REAL(KIND=LDP), PARAMETER :: RSEVEN=7.0_LDP
	REAL(KIND=LDP), PARAMETER :: REIGHT=8.0_LDP
	REAL(KIND=LDP), PARAMETER :: RNINE=9.0_LDP
	REAL(KIND=LDP), PARAMETER :: RTEN=10.0_LDP
!
	INTEGER, PARAMETER :: IZERO=0
	INTEGER, PARAMETER :: IONE=1
	INTEGER, PARAMETER :: ITWO=2
	INTEGER, PARAMETER :: ITHREE=3
	INTEGER, PARAMETER :: IFOUR=4
	INTEGER, PARAMETER :: IFIVE=5
	INTEGER, PARAMETER :: ISIX=6
	INTEGER, PARAMETER :: ISEVEN=7
	INTEGER, PARAMETER :: IEIGHT=8
	INTEGER, PARAMETER :: ININE=9
	INTEGER, PARAMETER :: ITEN=10
!
	END MODULE NUM_CONSTANTS_MOD	
