	MODULE SELECT_KIND
	IMPLICIT NONE
!
        INTEGER, PARAMETER :: LP=SELECTED_REAL_KIND(15,3000)
        REAL(KIND=LP), PARAMETER :: RZERO=0.0_LP
        REAL(KIND=LP), PARAMETER :: RONE=1.0_LP
        REAL(KIND=LP), PARAMETER :: RTWO=2.0_LP
!
	END MODULE SELECT KIND
	
