C       physical constants

	real*8 c_kms    ! c in km/sec
        parameter (c_kms=2.99792458d5)
	real*8 jimpi
	parameter (jimpi=3.141592653589793d0)
	real*8 zero
	parameter (zero=0d0)
	real*8 one
	parameter (one=1d0)
	real*8 two
	parameter (two=2d0)
	real*8 onehalf
	parameter (onehalf=0.5d0)
	logical true
	parameter (true=.true.)
	logical false
	parameter (false=.false.)
	logical forward
	parameter (forward=.true.)
	logical backward
	parameter (backward=.false.)
