	SUBROUTINE CREATE_GAUSS(XVEC,YVEC,LAM_CENT,SIGMA,HEIGHT,dX,NX)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER NX
	REAL(KIND=LDP) XVEC(NX)
	REAL(KIND=LDP) YVEC(NX)
	REAL(KIND=LDP) LAM_CENT
	REAL(KIND=LDP) dX
	REAL(KIND=LDP) SIGMA
	REAL(KIND=LDP) HEIGHT
!
	INTEGER I
	REAL(KIND=LDP) LAM_ST
!
	LAM_ST=LAM_CENT-NX*dX/2.0_LDP
	DO I=1,NX
	  XVEC(I)=LAM_ST+(I-1)*dX
	  YVEC(I)=1.0_LDP+HEIGHT*EXP(-0.5_LDP*((XVEC(I)-LAM_CENT)/SIGMA)**2 )
	END DO
!
	RETURN
	END
	
