	SUBROUTINE CREATE_GAUSS(XVEC,YVEC,LAM_CENT,SIGMA,HEIGHT,dX,NX)
	IMPLICIT NONE
!
	INTEGER NX
	REAL*8 XVEC(NX)
	REAL*8 YVEC(NX)
	REAL*8 LAM_CENT
	REAL*8 dX
	REAL*8 SIGMA
	REAL*8 HEIGHT
!
	INTEGER I
	REAL*8 LAM_ST
!
	LAM_ST=LAM_CENT-NX*dX/2.0D0
	DO I=1,NX
	  XVEC(I)=LAM_ST+(I-1)*dX
	  YVEC(I)=1.0D0+HEIGHT*EXP(-0.5D0*((XVEC(I)-LAM_CENT)/SIGMA)**2 )
	END DO
!
	RETURN
	END
	
