	SUBROUTINE CREATE_GAUSS(XVEC,YVEC,LAM_CENT,SIGMA,HEIGHT,dX,NX)
	IMPLICIT NONE
!
	INTEGER NX
	REAL(10) XVEC(NX)
	REAL(10) YVEC(NX)
	REAL(10) LAM_CENT
	REAL(10) dX
	REAL(10) SIGMA
	REAL(10) HEIGHT
!
	INTEGER I
	REAL(10) LAM_ST
!
	LAM_ST=LAM_CENT-NX*dX/2.0D0
	DO I=1,NX
	  XVEC(I)=LAM_ST+(I-1)*dX
	  YVEC(I)=1.0D0+HEIGHT*EXP(-0.5D0*((XVEC(I)-LAM_CENT)/SIGMA)**2 )
	END DO
!
	RETURN
	END
	
