	SUBROUTINE GET_ASSOC_ION(MATCHING_ION_LEV,NT)
	IMPLICIT NONE
!
	INTEGER NT
	INTEGER MATCHING_ION_LEV(NT)
!
	REAL Z,GION,MASS,ATNO
	INTEGER I,J,LU
	INTEGER NF,NS,NPHOT,EQN,ISPEC,ID
	CHARACTER(LEN=10) SPECIES(5*NT)
	CHARACTER(LEN=100) STRING
!
	CALL GET_LU(LU,'In GET_ASSOC_ION')
	OPEN(UNIT=LU,FILE='MODEL',STATUS='OLD',ACTION='READ')
	STRING=' '
	DO WHILE(INDEX(STRING,'Species') .EQ. 0)
	  READ(LU,'(A)')STRING
	END DO
	READ(LU,'(A)')STRING
	READ(LU,'(A)')STRING
!
	DO WHILE(1 .EQ. 1)
	  READ(LU,'(A)')STRING
	  IF(STRING .NE. ' ')THEN
	    IF(LEN_TRIM(STRING) .LT. 10)EXIT
	    READ(STRING(10:),*)NF,NS,Z,GION,MASS,ATNO,NPHOT,EQN,ISPEC,ID
	    MATCHING_ION_LEV(EQN:EQN+NS-1)=EQN+NS
	  END IF
	END DO
	CLOSE(LU)
!
	RETURN
	END
