	SUBROUTINE RD_ION_LOCATIONS_V2(FILENAME,ION_ID,NION,ION_INDEX,
	1               ZION,AT_NO,NUM_IONS,NMAX,LU_IN)
	IMPLICIT NONE
!
	INTEGER NMAX
	INTEGER LU_IN
	INTEGER NUM_IONS
	INTEGER NION(NMAX)
	INTEGER ION_INDEX(NMAX)
	REAL(10) ZION(NMAX)
	REAL(10) AT_NO(NMAX)
	CHARACTER(LEN=*) ION_ID(NMAX)
	CHARACTER(LEN=*) FILENAME
!
	REAL(10) T1
	INTEGER I,K
	CHARACTER(LEN=200) STRING
!
	ION_ID=' '
!
	OPEN(UNIT=LU_IN,FILE=FILENAME,STATUS='OLD',ACTION='READ')
	STRING=' '
	DO WHILE(INDEX(STRING,'Species') .EQ. 0)
	  READ(LU_IN,'(A)')STRING
	END DO
	READ(LU_IN,'(A)')STRING		!2nd header lines
	READ(LU_IN,'(A)')STRING		!Blank line
	READ(LU_IN,'(A)')STRING		!First species
!
	ION_INDEX=0
	NUM_IONS=0
	DO WHILE(1 .EQ. 1)
	  IF(STRING .NE. ' ')THEN
	    STRING=ADJUSTL(STRING)
	    K=INDEX(STRING,'  ')
	    NUM_IONS=NUM_IONS+1
	    ION_ID(NUM_IONS)=STRING(1:K-1)
	    READ(STRING(K:),*)I,NION(NUM_IONS),ZION(NUM_IONS),T1,T1,
	1                      AT_NO(NUM_IONS),I,ION_INDEX(NUM_IONS)
	  END IF 	
	  READ(LU_IN,'(A)')STRING
	  IF(STRING .EQ. ' ' .OR. LEN(TRIM(STRING)) .LT. 10)THEN
	    NUM_IONS=NUM_IONS+1
	    ION_ID(NUM_IONS)=TRIM(ION_ID(NUM_IONS-1))//'_ION'
	    NION(NUM_IONS)=1
	    ION_INDEX(NUM_IONS)=ION_INDEX(NUM_IONS-1)+NION(NUM_IONS-1)
	   END IF
	  IF(LEN(TRIM(STRING)) .LT. 10 .AND. STRING .NE. ' ')EXIT
	END DO
	CLOSE(LU_IN)
!
	OPEN(UNIT=LU_IN,FILE='ION_RD_CHK',STATUS='UNKNOWN')
	  DO K=1,NUM_IONS
	    WRITE(LU_IN,'(A,T10,I4,3X,I5,3X)')TRIM(ION_ID(K)),NION(K),ION_INDEX(K)
	  END DO
	CLOSE(LU_IN)
!
	RETURN
	END
