	SUBROUTINE SET_IP_XSPAT_UNIT(XV,P,XAXIS,RSTAR,DISTANCE,NP)
	USE MOD_USR_OPTION
	IMPLICIT NONE
!
	INTEGER NP
	REAL*8 XV(NP)
	REAL*8 P(NP)
	REAL*8 RSTAR
	REAL*8 DISTANCE
	CHARACTER(LEN=*) XAXIS
!
	CHARACTER(LEN=30) UC
	REAL*8 PARSEC
	EXTERNAL UC,PARSEC
!
	REAL*8 T1
	INTEGER K
	CHARACTER(LEN=10) XSPAT_UNIT
!
	CALL USR_OPTION(XSPAT_UNIT,'XSPAT','AU','Arc, CM, AU, P/R*')
	XSPAT_UNIT=UC(XSPAT_UNIT)
	IF(XSPAT_UNIT(1:3) .EQ. 'ARC')THEN
	  T1=1.0E+10*206265.0D0/(DISTANCE*1.0E+03*PARSEC())
	  DO K=1,NP-1
	    XV(K)=LOG10(P(K+1)*T1)
	  END DO
	  XAXIS='Log P(")'
	ELSE IF(XSPAT_UNIT(1:2) .EQ. 'AU')THEN
	  T1=1.496D+03
	  DO K=1,NP-1
	    XV(K)=LOG10(P(K+1)/T1)
	  END DO
	  XAXIS='Log P(AU)'
	ELSE IF(XSPAT_UNIT(1:2) .EQ. 'CM')THEN
	  DO K=1,NP-1
	    XV(K)=LOG10(P(K+1))
	  END DO
	  XAXIS='Log P(10\u10\d cm))'
	ELSE
	  XV(1:NP-1)=LOG10(P(2:NP)/RSTAR)
	  XAXIS='Log P/R\d*\u'
	END IF
!
	RETURN
	END
